=== markotallgren/XML/ajopaivakirja.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ajopaivakirja">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ajo" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alku">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:int" name="lukema" />
										<xs:element name="aika">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="kello"
															use="optional" />
														<xs:attribute type="xs:date" name="paiva"
															use="optional" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="paikka" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="loppu">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:int" name="lukema" />
										<xs:element name="aika">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="kello"
															use="optional" />
														<xs:attribute type="xs:date" name="paiva"
															use="optional" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="paikka" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="rekisterinro" />
			<xs:attribute type="xs:string" name="laatija" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== markotallgren/XML/ajopaivakirja.xml
<?xml version="1.0" encoding="UTF-8"?>
<ajopaivakirja rekisterinro="XYZ-123" laatija="Risto Reissaaja"
	xsi:noNamespaceSchemaLocation="ajopaivakirja.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ajo>
		<alku>
			<lukema>108497</lukema>
			<aika kello="11:20" paiva="2018-01-02" />
			<paikka>Ratapihantie 13, Helsinki</paikka>
		</alku>
		<loppu> 
			<lukema>108502</lukema>
			<aika kello="11:30" paiva="2018-01-02" />
			<paikka>Pajuniityntie 11, Helsinki</paikka>
		</loppu>
	</ajo>
	<ajo>
		<alku>
			<lukema>108502</lukema>
			<aika kello="13:00" paiva="2018-01-02" />
			<paikka>Pajuniityntie 11, Helsinki</paikka>
		</alku>
		<loppu>
			<lukema>108553</lukema>
			<aika kello="13:40" paiva="2018-01-02" />
			<paikka>Taidetehtaankatu 1, Porvoo</paikka>
		</loppu>
	</ajo>
	<ajo>
		<alku>
			<lukema>108553</lukema>
			<aika kello="16:00" paiva="2018-01-02" />
			<paikka>Taidetehtaankatu 1, Porvoo</paikka>
		</alku>
		<loppu>
			<lukema>108601</lukema>
			<aika kello="16:40" paiva="2018-01-02" />
			<paikka>Ratapihantie 13, Helsinki</paikka>
		</loppu>
	</ajo>
</ajopaivakirja>
